### ISSUE TITLE
URL Sharing for Blogs

### ISSUE THREAD

**Issue by shivambhargava33** [TeamArKa/VAYUZ-TPS#14]
URL Sharing for Blogs should show 
- Blog Banner
- Blog Title 
- Blog Description

Like - https://www.gaonconnection.com/samvad/water-crisis-rural-india-water-conservation-groundwater-recharge-water-shortage-rainwater-harvesting-53669

**Comment by VayuzBidyut** [comment]
@shivambhargava33 

Example of working one: https://en.gaonconnection.com/heat-wave-in-rural-india-was-once-waved-off-by-handmade-fanswhere-are-they-now/

If there's no SEO data in a blog, it won't show previews, if it exists it will show for sure.
